version: '2'

services:
  reverse-proxy:
    depends_on:
      - web-event-provider
      - web-kurlymall
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    restart: always

  web-event-provider:
    build:
      context: .
      dockerfile: apps/event-provider/Dockerfile
    environment:
      - PORT=3001
      - NEXT_PUBLIC_DOMAIN=events.local-kurly.com
    ports:
      - "3001:3001"
    restart: always

  web-kurlymall:
    build:
      context: .
      dockerfile: apps/kurlymall/Dockerfile
    environment:
      - PORT=3000
      - NEXT_PUBLIC_DOMAIN=www.local-kurly.com
    ports:
      - "3000:3000"
    restart: always